### ISSUE TITLE
Methode checkFourInARow(int spieler, int x, int y)  implementieren

### ISSUE THREAD

**Issue by Dudeldu** [ts12345/vier_gewinnt#12]
Die Methode soll per boolean zurückgeben, ob der Stein an der Stelle x,y in einer 4-Reihe ist

**Comment by Wor0r** [comment]
@ts12345 brauchen wir wirklich die x,y Koordinaten für checkFourInARow?

**Comment by ts12345** [comment]
Es reicht, wenn man jeweils nach dem Setzen eines Steines kontrolliert, ob
dadurch eine 4-Reihe entstanden ist.

Das Suchen auf dem ganzen Spielfeld ist nicht nötig und würde letztendlich auch
so aussehen, dass man alle Positionen durchgeht und kontrolliert, ob die
Position in einer 4-er Reihe ist.

Am 06.05.2016 um 18:26 schrieb Wor0r:
