### ISSUE TITLE
Class VIEW als JPanel implementieren und paintGraphics testweise überladen

### ISSUE THREAD

**Issue by ts12345** [ts12345/vier_gewinnt#15]
Die Klasse ähnlich wie beim "Game of Life" so gestalten, dass ein blaues Rechteck und ein roter Kreis angezeigt werden.

Zum Testen ist es nötig, in einer Testklasse (TEST_VIEW(?)) ein JFrame anzulegen und dort ein Objekt der Klasse zu adden:

Konstruktor TESTKLASSE:

```
    JFrame frameView = new JFrame("Vier gewinnt!");
    frameView.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE); 

    frameView.add(view);

    frameView.pack();
    frameView.setVisible(true);
```

**Comment by Stallian** [comment]
so theo...was hast du denn da angestellt?

**Comment by Stallian** [comment]
bis aufs Überladen ist alles ready.

**Comment by linoxlolatheo** [comment]
haichen
