### ISSUE TITLE
Klasse SOUNDENGINE anlegen

### ISSUE THREAD

**Issue by ts12345** [ts12345/vier_gewinnt#16]
Die Klasse SOUNDENGINE sollte mindestens folgende Methoden zur Verfügung stellen:
- playClick()  -- ein eingeworfener Stein macht "Klick!"
- playFanfare()  -- falls ein Spieler gewinnt, soll eine Fanfare ertönen

Anhaltspunkt:

http://noobtuts.com/java/play-sounds

Damit der Beispielcode läuft, braucht man einige Java-Klassen:

import java.io.File;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.sound.sampled.AudioInputStream;

**Comment by Wor0r** [comment]
Müssen nur noch die Sounds im Projektordner mit den Richtigen ersetzt werden.
