### ISSUE TITLE
Spiellogik im CONTROLLER

### ISSUE THREAD

**Issue by ts12345** [ts12345/vier_gewinnt#18]
Im Controller eine Methode spielStarten() umsetzen, die im Augenblick:

-- die beiden Computerspieler nach ihrem nächsten Zug befragt
-- das Spielfeld updatet
-- prüft, ob jemand gewonnen hat
-- falls jemand gewonnen hat, soll das dem Nutzer deutlich gemacht werden
-- Ausgabe des Spielfelds nach jedem Zug auf der Konsole

**Comment by hobbyduck** [comment]
changes lost... restarting issue

**Comment by hobbyduck** [comment]
der falsche gewinner wird angezeigt

**Comment by Dudeldu** [comment]
Leider noch nicht ganz glaube ich. Wenn man mit einem Computerspieler und einem Echten spielt , kann man zwei _ mal optimal setzen, dann geht es nicht mehr :(

**Comment by hobbyduck** [comment]
nö
