### ISSUE TITLE
Der VIEW soll auf Mausklicks reagieren -- EDIT: siehe #21

### ISSUE THREAD

**Issue by ts12345** [ts12345/vier_gewinnt#31]
Ein MouseListener muss hinzugefügt werden, der dafür sorgt, dass in der Spalte, auf die geklickt wurde, ein Spielstein gesetzt wird.

**Comment by Dudeldu** [comment]
Funktioniert, wenn man Klickt wird in die richtige Spalte gelegt. Problem : #19 funktioniert immernoch nicht -> Steine sind falsch angezeigt aber Klick wird nach senkrechten Spalten berechnet
