### ISSUE TITLE
Überlegen, wer Zugriff auf die SOUNDENGINE braucht

### ISSUE THREAD

**Issue by ts12345** [ts12345/vier_gewinnt#32]
Mach dir klar, wer Zugriff auf eine SOUNDENGINE braucht, um im richtigen Moment einen Sound abspielen zu können.

Notwendige Referenzattribute anlegen und initialisieren.

Das Modell sollte nichts mit dem User-Interface zu tun haben, damit später beide Teile unabhängig voneinander sind.

**Comment by SBaddmonn** [comment]
Controller ist für alles zuständig
