### ISSUE TITLE
Logik für den Startbildschirm überlegen

### ISSUE THREAD

**Issue by ts12345** [ts12345/vier_gewinnt#34]
Überlegen und festhalten (im DESIGN-Ordner), wie man vorgehen muss, um so einen Startbildschirm zu bekommen.

**Comment by ts12345** [comment]
Hilfreiches Video:

https://www.youtube.com/watch?v=FZWX5WoGW00

**Comment by SFr682k** [comment]
Enthalten in Issue #52
