### ISSUE TITLE
@alle: KOMMENTAR ZU DIESEM ISSUE LESEN

### ISSUE THREAD

**Issue by ts12345** [ts12345/vier_gewinnt#35]
Guten Morgen,

es kann ja sein, dass ihr Änderungen durchführt, es aber nicht schafft, diese zu pushen.

In diesem Fall:

Geänderte Dateien per Email an mich schicken!

An die Arbeit!
TS

**Comment by okamiii** [comment]
Die Carla hat ihr Passwort vergessen also hat sie einen neuen account erstellt und heißt jetzt neeeeeko
