### ISSUE TITLE
Gewinner in View ausgeben

### ISSUE THREAD

**Issue by SBaddmonn** [ts12345/vier_gewinnt#39]

**Comment by SBaddmonn** [comment]
```
public void Winner(int winner) 
{
    String str;
    if (winner==0){str = "Spieler 1 hat gewonnen!";}
    else{str = "Spieler 2 hat gewonnen!";}
    Graphics g = this.getGraphics();
    g.setColor(Color.GREEN);
    g.drawString(str, 30, 50);
}
```

**Comment by ts12345** [comment]
Die Ausgabe muss deutlich größer ausfallen!

(https://www.google.de/search?q=java+drawtext+fontsize)

**Comment by SBaddmonn** [comment]
```
/**
 * ändert interne Werte, damit der Gewinner in View ausgegeben wird
 */
public void showWinner (int winner)
{
    this.winner = winner;
    showWinner = true;
}
```

 if(showWinner) 
        {
            String str;
            if (winner==0){str = "Spieler 1 hat gewonnen!";}
            else{str = "Spieler 2 hat gewonnen!";}

```
        g.setColor(Color.GREEN);
        g.drawString(str, 30, 50);
    }
```

**Comment by SBaddmonn** [comment]
/**
- ändert interne Werte, damit der Gewinner in View ausgegeben wird
  */
  public void showWinner (int winner)
  {
  this.winner = winner;
  showWinner = true;
  }

if(showWinner)
{
String str;
if (winner==0){str = "Spieler 1 hat gewonnen!";}
else{str = "Spieler 2 hat gewonnen!";}

```
    g.setColor(Color.GREEN);
    g.drawString(str, 300, 500);
}
```
