### ISSUE TITLE
Im CONTROLLER: spielStarten überarbeiten

### ISSUE THREAD

**Issue by ts12345** [ts12345/vier_gewinnt#48]
Folgendes Problem ist aufgetreten, als ich einen Bot programmiert habe:

Die Spielsteine des Bots sind, egal ober er als Erster oder als Zweiter gesetzt hat, immer mit 1 im Spielfeld kodiert worden. Die Steine des Menschen immer mit 2.

Ursache dafür ist, dass

```
    players[0]=new COMPUTERSPIELER_TS(spielfeld);
    players[1]=new HUMANSPIELER(frameView);
```

und danach ausgelost wird, wer anfängt.
Ändert man auf 

```
    players[1]=new COMPUTERSPIELER_TS(spielfeld);
    players[0]=new HUMANSPIELER(frameView);
```

so ist der Bot immer 2 und der Mensch immer 1 im spielfeld.

Das sollte so nicht sein. Die Nummer 1 auf dem Brett sollte signalisieren, dass das der Spieler ist, der angefangen hat.

Dazu könnte man wie folgt vorgehen, damit trotzdem ausgelost wird, wer anfagen darf.

```
    players[0]=new COMPUTERSPIELER_TS(spielfeld);
    players[1]=new HUMANSPIELER(frameView);

   zufallszahl <- 0 oder 1

  SPIELER spielerEins = players[zufallszahl]
  SPIELER spielerZwei = players[1 - zufallszahl]

 und ab diesem Zeitpunkt nur noch mit spielerEins und spielerZwei arbeiten.
```

**Comment by SFr682k** [comment]
Issue hat sich erledigt; Problem wurde durch Umstieg auf Netzwerkspiel und dadurch erfolgte Festlegung der Spielernummer im BATCH-Starter "gelöst"

Die Klasse COMPUTERSPIELER_TS wurde bereits so geändert, dass es funktioniert
