### ISSUE TITLE
Irgendetwas für das Spielende erstellen

### ISSUE THREAD

**Issue by SFr682k** [ts12345/vier_gewinnt#51]
Zusätzlich zur bereits bestehenden Animation für den freien Fall könnte man das Feld nicht von jetzt auf gleich "ausleeren", sondern ein Herausfallen der Steine nach unten simulieren

**Comment by hobbyduck** [comment]
Es geht noch nicht und gibt einige Probleme, deswegen ist die Aufrufmethode jetzt erstmal auskommentiert, habe den STEINTHREAD wohl noch nicht ganz verstanden.

**Comment by hobbyduck** [comment]
Immerhin musste ich nur zweimal alle sachen neu runterladen und mit meinem code aktualisieren um einen gültigen commit zu machen

**Comment by Wor0r** [comment]
Ich weiß nicht ob wir noch was brauchen, aber ich schließe es trotzdem.
